name: CI

on:
  push:
    branches: [ master, dev, development, 'version-*' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, dev, development ]

jobs:
  build:
    name: Build (${{ matrix.platform }}, ${{ matrix.configuration }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [win32, x64, arm64]
        configuration: [debug, release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake --preset ${{ matrix.platform }}-${{ matrix.configuration }} "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build --preset ${{ matrix.platform }}-${{ matrix.configuration }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: explorerpp-${{ matrix.platform }}-${{ matrix.configuration }}
        path: |
          build/${{ matrix.platform }}-${{ matrix.configuration }}/bin/Explorer++.exe
          build/${{ matrix.platform }}-${{ matrix.configuration }}/bin/Explorer++*.dll
